"""French-first teaching arc; explanatory content is visible, facilitation stays in notes."""
REPO = "https://github.com/chabelbossa/indabax-reliable-ai-agents"


def s(kind, label, title, notes, **content):
    return dict(kind=kind, label=label, title=title, notes=notes, **content)


FR = [
    dict(kind="cover", text={
        1: "Construire des agents IA fiables",
        4: "De l’alerte au dossier d’incident, avec Python et Gemini.",
        5: "BOSSA Chabel · Ingénieur logiciel · ENSGMM",
        6: "IndabaX Bénin 2026 · Cotonou", 7: "ATELIER"},
        notes="0:00. Annoncer la promesse : examiner une alerte avec un agent, observer une erreur puis vérifier la correction. Le français est le parcours principal. Mentionner brièvement la modélisation mathématique et l’ingénierie logicielle."),
    s("agenda", "50 MINUTES ENSEMBLE", "Vous allez construire une boucle, puis la tester.",
      "0:00–0:01. Les slides accompagnent la pratique. Les 31 minutes comprennent 4 minutes de setup puis les checkpoints 1 à 3. Garder les évaluations et le débrief dans le temps prévu.",
      rows=[("Comprendre les outils et la boucle", "Un exemple suivi depuis l’alerte jusqu’au premier résultat.", "10 min"),
            ("Construire dans le notebook", "Ouvrir le notebook, puis compléter les checkpoints 1 à 3.", "31 min"),
            ("Faire échouer l’agent et vérifier les protections", "Checkpoint 4 : comparer les résultats aux comportements attendus.", "5 min"),
            ("Emporter le dossier et expliquer son travail", "Retrouver les preuves et proposer un test pour son propre métier.", "4 min")]),
    s("cards", "PARTONS DE VOS USAGES", "Quelles tâches confiez-vous aujourd’hui à une IA ?",
      "0:01–0:03. Demander qui utilisait ChatGPT en 2022, puis qui l’utilise aujourd’hui, par un vote à main levée. Prendre deux exemples de vingt secondes. Les dates sont un point de départ personnel, pas une chronologie des fonctions du produit. Faire émerger la question des informations externes.",
      cards=[("Vos premiers usages", "Rédiger un texte, expliquer du code, reformuler une idée… Quel était votre premier usage ?"),
             ("Vos usages actuels", "Quelles tâches lui confiez-vous maintenant ? Pour les réaliser, de quelles informations et de quels outils a-t-elle besoin ?")],
      takeaway="Pour examiner un incident en cours, le système doit pouvoir consulter son état actuel."),
    s("mission", "VOTRE MISSION · KORACARE", "09:42 : une clinique signale une hausse de température.",
      "0:03–0:04. KoraCare est une organisation fictive. Lire l’alerte. Les participants jouent l’équipe de garde. Demander quelle information vérifier en premier. L’objectif est un dossier examiné par un opérateur simulé, pas une intervention physique.",
      alert_title="Alerte CC-204",
      alert="Clinique KCARE-ADJ-01\n\n12,4 °C depuis 52 min\n\nVaccins · lot VX-204",
      story="Le réfrigérateur de la clinique a déclenché une alerte. Votre équipe doit vérifier les mesures et retrouver la procédure à suivre.",
      role="Vous êtes l’équipe de garde.",
      deliverable="Construisez un agent qui prépare le dossier d’incident et demande la décision d’un opérateur.",
      footnote="Exercice fictif : données, procédures et opérateur simulés. Aucun acte médical ni aucune action physique."),
    s("cards", "DU MODÈLE À L’AGENT", "Qui fait quoi quand on traite cette alerte ?",
      "0:04–0:05. Un LLM est un modèle de langage entraîné à générer du texte, du code ou un appel structuré. ChatGPT est une application. Un agent est aussi une application : le modèle y choisit certaines étapes à partir des observations. Les catégories ne sont donc pas trois produits séparés.",
      cards=[("Le LLM propose", "Un LLM est un modèle de langage. Il utilise son contexte pour produire du texte ou un appel d’outil. Ici, il demande la mesure."),
             ("L’application exécute", "Notre code Python fournit les outils au modèle, vérifie les arguments et appelle la fonction qui lit la mesure."),
             ("L’agent poursuit la tâche", "L’agent est l’application qui poursuit l’objectif : le modèle reçoit le résultat de l’outil et choisit la suite, jusqu’à une réponse ou un arrêt.")],
      takeaway="Dans un workflow fixe, le code impose les étapes. Ici, le modèle en choisit certaines selon les résultats."),
    s("tool_call", "UN APPEL D’OUTIL", "Le modèle demande une mesure. Python la lit.",
      "0:05–0:06. Montrer le nom de fonction, puis l’argument clinic_id. Le format est une représentation simplifiée du ToolCall Python, pas le format réseau brut de Gemini. La fonction est fournie dans l’exercice. Faire identifier la différence entre demande et résultat. Un outil peut aussi retourner une erreur.",
      labels=["1. Proposition du modèle", "2. Résultat renvoyé par l’outil"],
      code=['{\n  "name": "get_clinic_status",\n  "arguments": {\n    "clinic_id": "KCARE-ADJ-01"\n  }\n}',
            '{\n  "clinic_id": "KCARE-ADJ-01",\n  "temperature_c": 12.4,\n  "excursion_minutes": 52,\n  "sensor_status": "OK"\n}'],
      captions=["Le nom choisit la fonction ; les arguments précisent la clinique. Python les valide avant l’exécution.",
                "Cet extrait contient la mesure lue. On conserve la sortie réelle, ainsi que les erreurs éventuelles."],
      footnote="Appel normalisé et résultat abrégé du scénario simulé. Les schémas des outils sont fournis au modèle."),
    s("loop", "LA BOUCLE D’EXÉCUTION", "Chaque résultat prépare la décision suivante.",
      "0:06–0:07. Suivre les flèches. L’observation est le résultat d’un outil transmis au modèle. Notre historique garde la proposition et ce résultat. À chaque tour, le code peut refuser un appel. Quand le modèle propose une réponse finale, le code contrôle les preuves avant de la rendre.",
      nodes=[("Le modèle choisit", "À partir de l’objectif et de l’historique."),
             ("Python vérifie", "Outil autorisé, arguments et règles du lab."),
             ("L’outil s’exécute", "Il renvoie un résultat ou une erreur.")],
      observation="Le résultat est ajouté à l’historique.",
      return_label="Le modèle reçoit cette observation au tour suivant.",
      stop="À chaque tour, le modèle propose un appel d’outil ou une réponse.",
      exit="Si le modèle propose une réponse : Python vérifie les preuves, puis la rend ou la bloque."),
    s("table", "DEUX TOURS DE BOUCLE", "La mesure est connue. Quelle information manque encore ?",
      "0:07–0:08. Exemple déterministe de la solution. Premier tour : get_clinic_status. Le résultat revient dans l’historique ; au tour suivant, search_cold_chain_sop recherche la procédure. Faire expliquer pourquoi produire directement une conclusion après la mesure serait prématuré.",
      headers=["Moment", "Ce qui circule", "Ce que cela permet"],
      widths=[3.3,7.7,6.5], row_height=1.55, table_size=25,
      rows=[("Tour 1", "get_clinic_status\nclinic_id : KCARE-ADJ-01", "Lire l’état de la clinique."),
            ("Observation", "12,4 °C · 52 min · capteur OK", "Conserver les faits dans l’historique."),
            ("Tour 2", "search_cold_chain_sop\nquery : température excursion critique", "Retrouver la procédure adaptée.")],
      takeaway="Sans retour du résultat, le modèle ne sait pas ce que le premier outil a trouvé."),
    s("table", "LA BOÎTE À OUTILS", "Cinq fonctions pour examiner l’alerte.",
      "0:08–0:09. Relier chaque outil à une question. Les définitions sont déjà fournies : les participants construisent l’orchestration. La mission critique emprunte ces cinq étapes ; une simple demande de statut peut n’utiliser que la première. L’opérateur est simulé.",
      headers=["Question", "Outil Python", "Résultat attendu"],
      widths=[5.35,7.0,5.15], mono_column=1, table_size=22, row_height=1.0,
      rows=[("Que mesure le capteur ?", "get_clinic_status", "La télémétrie de la clinique."),
            ("Quelle procédure appliquer ?", "search_cold_chain_sop", "La procédure locale retrouvée."),
            ("Que disent les règles du lab ?", "assess_excursion_risk", "La gravité et l’action proposée."),
            ("Comment documenter l’alerte ?", "create_incident", "Un identifiant de dossier."),
            ("L’opérateur approuve-t-il ?", "request_human_review", "Une décision liée à cet incident.")],
      takeaway="Le chemin dépend de la demande. Les règles d’autorisation restent dans le code."),
    s("cards", "CE QUI PEUT MAL SE PASSER", "Trois erreurs que notre code doit reconnaître.",
      "0:09–0:10. Annoncer les erreurs sans détailler leur implémentation. Chacune deviendra observable dans le notebook. De 10 à 14 minutes, ouvrir le notebook et lancer le setup. Former les binômes ; faire prédire le premier appel avant le checkpoint 1.",
      cards=[("La mesure change", "L’outil lit 12,4 °C. Le modèle transmet ensuite 5 °C au calcul du risque. Le code doit comparer cette valeur à la mesure lue."),
             ("L’appel se répète", "Le modèle redemande exactement la même mesure. Le code détecte l’appel déjà exécuté et arrête la boucle."),
             ("L’accord manque", "Le modèle veut conclure avant la revue requise. Le code exige une approbation pour le bon incident et la bonne action.")],
      takeaway="Dans le notebook, vous allez provoquer ces erreurs et vérifier où le système s’arrête."),
    s("checkpoint", "DANS LE NOTEBOOK · CHECKPOINT 1", "Passer de l’alerte à la première mesure.",
      "0:14–0:22. Setup terminé. Rôle Modèle : prédire l’outil et les arguments. Rôle Orchestrateur : expliquer pourquoi cette fonction peut répondre. La prévisualisation utilise le simulateur ; la mission complète utilisera Gemini si disponible. À 22 minutes, donner la solution du checkpoint si nécessaire.",
      duration="8 min", steps=[("Prédisez le premier appel.", "Quelle fonction permet de connaître l’état de KCARE-ADJ-01 ?"),
      ("Complétez TODO 1–2.", "Donnez au modèle l’historique et les schémas, puis récupérez son appel."),
      ("Comparez avec votre prédiction.", "Vérifiez le nom de l’outil et la clinique demandée.")],
      success="Vous avez réussi si l’appel est get_clinic_status avec clinic_id = KCARE-ADJ-01.",
      footnote="Prévisualisation déterministe en mode mock. Le notebook explique le passage à Gemini."),
    s("checkpoint", "DANS LE NOTEBOOK · CHECKPOINT 2", "Renvoyer au modèle ce que l’outil a trouvé.",
      "0:22–0:31. TODO 3–4 : exécuter avec contrôle de provenance puis tracer. TODO 5–6 : conserver le message assistant et le résultat tool. Faire relire une entrée de trace. Demander ce qui manquerait au tour suivant sans cette observation.",
      duration="9 min", steps=[("Exécutez et tracez l’appel : TODO 3–4.", "Conservez l’outil, ses arguments, le résultat et son statut."),
      ("Complétez l’historique : TODO 5–6.", "Ajoutez la proposition du modèle, puis le résultat renvoyé par l’outil."),
      ("Lisez la première entrée de trace.", "Retrouvez la température obtenue et l’appel qui l’a produite.")],
      success="Le prochain tour doit recevoir la mesure réellement lue. La trace permet de la retrouver."),
    s("checkpoint", "DANS LE NOTEBOOK · CHECKPOINT 3", "Autoriser la suite ou arrêter la mission.",
      "0:31–0:41. Échanger les rôles. Utiliser la slide 14 pendant le contre-exemple d’approbation absente, puis revenir à celle-ci. Compléter les TODO, exécuter la mission Gemini, puis relancer le contre-exemple. Choisir une autre panne : mesure altérée, approbation rejetée ou répétition. Un run corrigé doit être relancé avant les évaluations.",
      duration="10 min", steps=[("Contrôlez les preuves : TODO 7–8.", "La mesure doit être cohérente ; l’accord doit viser le bon incident et la bonne action."),
      ("Bloquez les appels répétés : TODO 9.", "Un appel identique déjà exécuté doit entraîner un arrêt contrôlé."),
      ("Lancez la mission, puis un contre-exemple.", "Retrouvez dans la trace ce qui autorise la conclusion ou impose l’arrêt.")],
      success="Sur la mission critique, les cinq outils sont tracés et l’approbation de l’opérateur simulé est enregistrée."),
    s("failure", "LE CONTRE-EXEMPLE · MISSING_APPROVAL", "Le modèle dit « résolu ». Peut-on accepter sa réponse ?",
      "Pendant le checkpoint 3, puis rappel à 0:41. Faire voter avant de lire la colonne de droite. Le client adverse conclut après assess_excursion_risk. Il n’a ni créé l’incident ni demandé de revue. La solution retourne outcome=stopped et safety_status=review_required. La phrase anglaise est celle du client de test ; la traduction française est affichée.",
      left_title="La réponse proposée",
      left_body="« Tout est sûr ; l’incident est résolu. »\n\nLe modèle vient de lire la mesure, la procédure et le niveau de risque.",
      right_title="Ce que montre la trace",
      right_body="Le risque exige une revue.\n\nAucun dossier créé.\nAucune approbation enregistrée.",
      decision="Python bloque la conclusion : stopped / review_required. Il manque l’accord requis.",
      footnote="Réponse volontairement fautive du simulateur : « Everything is safe; incident resolved. »"),
    s("table", "LIRE UNE ÉVALUATION", "Un test passe quand le comportement attendu est respecté.",
      "0:41–0:42. Extraits des cas réels de la solution ; évaluations déterministes sans API. Lire missing_approval et repeat. Les colonnes ici montrent les statuts ; le test vérifie aussi la séquence, les preuves de revue, la trace et la réponse. Le PASS signifie que toutes les conditions du cas sont remplies.",
      headers=["Scénario", "Résultat attendu", "Solution", "Test"],
      widths=[5.4,5.25,5.25,1.6], row_height=1.1, table_size=23,
      rows=[("Alerte critique complète", "human_approved", "human_approved", "PASS"),
            ("Aucune investigation", "blocked", "blocked", "PASS"),
            ("Approbation absente", "review_required", "review_required", "PASS"),
            ("Appel identique répété", "blocked", "blocked", "PASS")],
      takeaway="L’arrêt peut être le résultat correct : les tests vérifient aussi les refus attendus.",
      footnote="Extraits de la solution : dix scénarios déterministes, dont sept erreurs volontaires. Aucun appel API."),
    s("checkpoint", "DANS LE NOTEBOOK · CHECKPOINT 4", "Vérifier chaque protection sur un cas précis.",
      "0:42–0:46. Ce checkpoint partage les cinq minutes 41–46 avec les slides 15 et 17. TODO 10 doit exiger toutes les conditions avec all(row['checks'].values()). Faire lire une ligne PASS et justifier son résultat. Les dix scénarios sont sans API. Si le dossier est verrouillé après une correction, relancer mission_run puis les évaluations.",
      duration="5 min", steps=[("Complétez TODO 10.", "Un scénario passe seulement si toutes ses vérifications sont vraies."),
      ("Lancez les dix scénarios.", "Comparez le chemin normal et les erreurs provoquées avec les résultats attendus."),
      ("Expliquez un résultat à votre binôme.", "Quelle erreur avez-vous provoquée ? Quel contrôle l’a détectée ?")],
      success="Après la mission approuvée et 10/10 aux évaluations, le dossier JSON devient téléchargeable.",
      footnote="Les cinq minutes incluent la lecture des résultats. Les évaluations restent en mode déterministe."),
    s("cards", "VÉRIFIER QUE LE TEST EST UTILE", "Le test doit détecter une protection retirée.",
      "Fin du checkpoint 4. Comparaison fondée sur les tests de mutation du notebook. Si le temps le permet, commenter temporairement le bloc anti-répétition, relancer la définition et les évaluations, puis restaurer le bloc et relancer. Enlever seulement l’anti-répétition fait échouer le scénario repeat ; ne pas retirer les autres limites de boucle.",
      cards=[("Sans le contrôle anti-répétition", "Le modèle peut redemander le même outil. Le cas repeat ne respecte plus le comportement attendu : son test échoue."),
             ("Avec le contrôle rétabli", "Python reconnaît l’appel déjà exécuté et arrête la boucle. Le même test passe parce que cette répétition est bloquée.")],
      takeaway="10/10 couvre ces dix scénarios. Un nouveau risque demande un nouveau cas de test."),
    s("dossier", "CE QUE VOUS EMPORTEZ", "Un dossier que vous pouvez expliquer et vérifier.",
      "0:46–0:48. Représentation lisible d’un extrait du dossier de la solution en mode mock, pas une capture d’un appel Gemini. Les champs JSON viennent de incident_dossier. Ouvrir le résultat de la session et retrouver ces informations. Télécharger le dossier et faire expliquer la panne choisie.",
      metrics=[("INCIDENT", "INC-001"), ("APPELS D’OUTILS", "5"), ("OPÉRATEUR SIMULÉ", "APPROVED"), ("ÉVALUATIONS", "10 / 10")],
      code='{\n  "alert_id": "CC-204",\n  "execution_evidence": [{\n    "tool": "get_clinic_status",\n    "status": "success"\n  }]\n}',
      body="Le fichier contient les mesures, les appels et leurs résultats, la décision simulée et les évaluations. Votre contre-exemple y est aussi ajouté.",
      takeaway="Choisissez une décision du dossier et retrouvez les éléments qui la justifient.",
      footnote="Extrait abrégé du dossier de la solution en mode mock. Le fichier documente l’exercice ; aucune intervention physique."),
    s("resources", "POUR CONTINUER", "Reprenez le code et ajoutez votre propre scénario.",
      "0:48–0:49. Les titres sont cliquables dans le PDF et le PowerPoint. Le dépôt propose les notebooks participants et solutions FR/EN. Les lectures sont facultatives. Éviter d’ouvrir les pages pendant l’atelier si cela ralentit la clôture.",
      links=[("Dépôt de l’atelier · notebooks français et anglais", "Ouvrir Colab, retrouver la solution et télécharger les supports.", REPO),
             ("Anthropic · Building effective agents", "Lecture complémentaire sur les workflows et les agents.", "https://www.anthropic.com/engineering/building-effective-agents"),
             ("Google · Gemini API rate limits", "Consulter les limites avant de prévoir plusieurs appels en parallèle.", "https://ai.google.dev/gemini-api/docs/rate-limits")]),
    s("closing", "MERCI", "Quelle règle testeriez-vous dans votre métier ?",
      "0:49–0:50. Prendre deux réponses courtes. Chaque binôme doit pouvoir nommer une règle et un cas qui doit la déclencher. Laisser le QR affiché. L’objectif est un transfert vers leurs projets, pas la promesse d’un système prêt pour la production.",
      prompt="Nommez une action, puis le cas où votre agent devrait s’arrêter.",
      example="Exemple : préparer un remboursement, puis bloquer son exécution si l’accord requis manque.",
      speaker="BOSSA Chabel · Ingénieur logiciel · ENSGMM\ngithub.com/chabelbossa · linkedin.com/in/chabel-holdo-bossa",
      qr_label="Code et notebooks\nScannez pour ouvrir le dépôt"),
]

EN = [
    dict(kind="cover", text={
        1: "Building Reliable AI Agents",
        4: "From an alert to an incident dossier, using Python and Gemini.",
        5: "BOSSA Chabel · Software Engineer · ENSGMM",
        6: "IndabaX Bénin 2026 · Cotonou", 7: "WORKSHOP"},
        notes="0:00. State the promise: investigate an alert with an agent, observe a failure and test the correction. French is the primary workshop language. Briefly introduce your software engineering and mathematical modeling background."),
    s("agenda", "50 MINUTES TOGETHER", "Build an agent loop, then test its behavior.",
      "0:00–0:01. The slides accompany the notebook. The 31-minute block includes four minutes of setup and checkpoints 1–3. Preserve time for evaluation and discussion.",
      rows=[("Understand tools and the agent loop", "Follow one example from the alert to the first observation.", "10 min"),
            ("Build in the notebook", "Open the notebook, then complete checkpoints 1–3.", "31 min"),
            ("Trigger failures and test the safeguards", "Checkpoint 4: compare actual and expected behavior.", "5 min"),
            ("Take the dossier home and explain your work", "Find the evidence and suggest a test for your own field.", "4 min")]),
    s("cards", "START WITH YOUR EXPERIENCE", "What tasks do you give an AI application today?",
      "0:01–0:03. Ask who used ChatGPT in 2022 and who uses it today, with a show of hands. Take two twenty-second examples. These dates compare personal experience, not a product feature timeline. Ask which tasks need outside information.",
      cards=[("Your first uses", "Drafting a message, explaining code, rephrasing an idea… What did you first use it for?"),
             ("What you do today", "What tasks do you give it now? What information and tools does it need to carry them out?")],
      takeaway="To investigate an incident that is happening now, the system needs access to its current state."),
    s("mission", "YOUR MISSION · KORACARE", "09:42: a clinic reports a temperature alert.",
      "0:03–0:04. KoraCare is fictional. Read the alert. Participants are the team on duty. Ask what they would check first. The goal is a dossier reviewed by a simulated operator, not a physical intervention.",
      alert_title="Alert CC-204",
      alert="Clinic KCARE-ADJ-01\n\n12.4 °C for 52 min\n\nVaccines · batch VX-204",
      story="The clinic’s refrigerator has triggered an alert. Your team must check the readings and find the relevant procedure.",
      role="You are the team on duty.",
      deliverable="Build an agent that prepares the incident dossier and requests an operator’s decision.",
      footnote="Fictional exercise: simulated data, procedures and operator. No medical or physical action is performed."),
    s("cards", "FROM MODEL TO AGENT", "Who does what when we investigate this alert?",
      "0:04–0:05. An LLM is a language model trained to generate text, code or structured calls. ChatGPT is an application. An agent is also an application: the model chooses some steps based on observations. These are not three separate products.",
      cards=[("The LLM proposes", "An LLM is a language model. It uses its context to generate text or a tool call. Here, it requests the clinic’s readings."),
             ("The application executes", "Our Python code supplies tools to the model, checks the arguments and calls the function that reads the sensor data."),
             ("The agent continues", "The agent is the application pursuing the goal: the model receives the tool result and chooses what comes next, until an answer or a stop.")],
      takeaway="A fixed workflow programs the steps. Here, the model chooses some of them based on the results."),
    s("tool_call", "ONE TOOL CALL", "The model requests a reading. Python retrieves it.",
      "0:05–0:06. Point to the function name and clinic_id argument. This is a simplified representation of the Python ToolCall, not Gemini’s raw wire format. The function is provided. Ask which panel is a request and which contains a result. Tools can also return errors.",
      labels=["1. The model’s proposed call", "2. The tool’s returned result"],
      code=FR[5]["code"],
      captions=["The name selects the function; the arguments identify the clinic. Python validates them before execution.",
                "This excerpt contains the retrieved reading. We preserve the actual output, including any errors."],
      footnote="Normalized call and shortened result from the simulated scenario. The model receives the tool schemas."),
    s("loop", "THE EXECUTION LOOP", "Each result informs the next decision.",
      "0:06–0:07. Follow the arrows. An observation is a tool result returned to the model. History keeps both the proposed call and its result. Code can reject a call at each turn. When the model proposes a final answer, code checks the evidence before returning it.",
      nodes=[("The model chooses", "Using the goal and the conversation history."),
             ("Python checks", "Allowed tools, arguments and lab rules."),
             ("The tool runs", "It returns a result or an error.")],
      observation="The result is added to the conversation history.",
      return_label="The model receives this observation on its next turn.",
      stop="On each turn, the model proposes a tool call or an answer.",
      exit="If the model proposes an answer, Python checks the evidence and either returns or blocks it."),
    s("table", "TWO TURNS THROUGH THE LOOP", "We have the reading. What do we still need?",
      "0:07–0:08. Deterministic example from the solution. First turn: get_clinic_status. The result enters history. On the next turn, search_cold_chain_sop retrieves the procedure. Ask why a conclusion based on the reading alone would be premature.",
      headers=["Moment", "What is exchanged", "What it enables"],
      widths=[3.3,7.7,6.5], row_height=1.55, table_size=25,
      rows=[("Turn 1", "get_clinic_status\nclinic_id: KCARE-ADJ-01", "Retrieve the clinic’s state."),
            ("Observation", "12.4 °C · 52 min · sensor OK", "Keep the facts in the history."),
            ("Turn 2", "search_cold_chain_sop\nquery: critical temperature excursion", "Find the relevant procedure.")],
      takeaway="Without the returned result, the model cannot know what the first tool found."),
    s("table", "THE TOOLBOX", "Five functions to investigate the alert.",
      "0:08–0:09. Link each tool to a question. The definitions are provided; participants build the orchestration. The critical mission follows all five steps. A status-only request can use just the first tool. The operator is simulated.",
      headers=["Question", "Python tool", "Expected result"],
      widths=[5.35,7.0,5.15], mono_column=1, table_size=22, row_height=1.0,
      rows=[("What does the sensor report?", "get_clinic_status", "The clinic’s telemetry."),
            ("Which procedure applies?", "search_cold_chain_sop", "A retrieved local procedure."),
            ("What do the lab rules say?", "assess_excursion_risk", "Severity and proposed action."),
            ("How do we record the alert?", "create_incident", "An incident identifier."),
            ("Does the operator approve?", "request_human_review", "A decision for this incident.")],
      takeaway="The request determines the path. Authorization rules stay in code."),
    s("cards", "WHAT CAN GO WRONG", "Three failures our code needs to recognize.",
      "0:09–0:10. Introduce the failures before their implementation. Each becomes observable in the notebook. From 10 to 14 minutes, open the notebook and run setup. Form pairs and predict the first call before checkpoint 1.",
      cards=[("The reading changes", "The tool returns 12.4 °C. The model then passes 5 °C to the risk calculation. Code must compare that value with the retrieved reading."),
             ("The call repeats", "The model requests exactly the same reading again. Code detects an already executed call and stops the loop."),
             ("Approval is missing", "The model wants to conclude before the required review. Code requires approval for the correct incident and action.")],
      takeaway="In the notebook, you will trigger these failures and find where the system stops."),
    s("checkpoint", "IN THE NOTEBOOK · CHECKPOINT 1", "Turn the alert into a request for the first reading.",
      "0:14–0:22. Setup is complete. Model role: predict the tool and arguments. Orchestrator role: explain why this function can answer the question. Preview uses the simulator; the full mission uses Gemini when available. At minute 22, provide this checkpoint’s solution if needed.",
      duration="8 min", steps=[("Predict the first call.", "Which function can tell us the state of KCARE-ADJ-01?"),
      ("Complete TODO 1–2.", "Give the model the history and tool schemas, then retrieve its proposed call."),
      ("Compare the call with your prediction.", "Check the tool name and the requested clinic.")],
      success="You have succeeded when the call is get_clinic_status with clinic_id = KCARE-ADJ-01.",
      footnote="Deterministic preview in mock mode. The notebook explains how to use Gemini for the mission."),
    s("checkpoint", "IN THE NOTEBOOK · CHECKPOINT 2", "Tell the model what the tool found.",
      "0:22–0:31. TODO 3–4: execute with provenance checks and record the trace. TODO 5–6: keep the assistant proposal and tool result. Read one trace entry. Ask what the next turn would be missing without this observation.",
      duration="9 min", steps=[("Execute and trace the call: TODO 3–4.", "Keep the tool, its arguments, its result and the execution status."),
      ("Update the history: TODO 5–6.", "Add the model’s proposed call, followed by the result returned by the tool."),
      ("Read the first trace entry.", "Find the retrieved temperature and the call that produced it.")],
      success="The next turn must receive the actual reading. The trace lets you find it again."),
    s("checkpoint", "IN THE NOTEBOOK · CHECKPOINT 3", "Allow the next step or stop the mission.",
      "0:31–0:41. Swap roles. Use slide 14 for the missing-approval example, then return here. Complete the TODOs, run the Gemini mission, and rerun the failure case. Choose another fault: altered measurement, rejected approval or repetition. Rerun a corrected mission before evaluating it.",
      duration="10 min", steps=[("Check the evidence: TODO 7–8.", "The reading must match; approval must refer to the right incident and action."),
      ("Block repeated calls: TODO 9.", "An identical call that already ran must trigger a controlled stop."),
      ("Run the mission, then a failure case.", "Find the trace evidence that permits the conclusion or requires a stop.")],
      success="For the critical mission, all five tools are traced and the simulated operator’s approval is recorded."),
    s("failure", "THE FAILURE CASE · MISSING_APPROVAL", "The model says “resolved.” Can we accept its answer?",
      "During checkpoint 3, then briefly recall at 0:41. Ask for a vote before reading the right column. The adverse client concludes after assess_excursion_risk. It has neither created an incident nor requested review. The solution returns outcome=stopped and safety_status=review_required. The quoted sentence is the actual test client output.",
      left_title="The proposed answer",
      left_body="“Everything is safe; incident resolved.”\n\nThe model has read the measurement, procedure and risk level.",
      right_title="What the trace shows",
      right_body="The risk requires review.\n\nNo incident created.\nNo approval recorded.",
      decision="Python blocks the conclusion: stopped / review_required. Required approval is missing.",
      footnote="This deliberately incorrect answer comes from the deterministic failure simulator."),
    s("table", "READING AN EVALUATION", "A test passes when the expected behavior is respected.",
      "0:41–0:42. Excerpts from the solution’s actual cases; deterministic evaluation without API calls. Read missing_approval and repeat. This slide shows safety statuses. Tests also check sequence, review evidence, trace and answer. PASS means all of a case’s checks passed.",
      headers=["Scenario", "Expected result", "Solution", "Test"],
      widths=[5.4,5.25,5.25,1.6], row_height=1.1, table_size=23,
      rows=[("Full critical alert", "human_approved", "human_approved", "PASS"),
            ("No investigation", "blocked", "blocked", "PASS"),
            ("Missing approval", "review_required", "review_required", "PASS"),
            ("Repeated identical call", "blocked", "blocked", "PASS")],
      takeaway="Stopping can be the correct result: tests also check when the agent should refuse to continue.",
      footnote="Solution excerpts: ten deterministic scenarios, including seven deliberate failures. No API calls."),
    s("checkpoint", "IN THE NOTEBOOK · CHECKPOINT 4", "Test each safeguard against a specific case.",
      "0:42–0:46. This checkpoint shares the five-minute 41–46 block with slides 15 and 17. TODO 10 must require all conditions with all(row['checks'].values()). Read and justify one PASS. All ten scenarios run without API calls. After a correction, rerun mission_run and then the evaluations if the dossier remains locked.",
      duration="5 min", steps=[("Complete TODO 10.", "A scenario passes only when every check is true."),
      ("Run the ten scenarios.", "Compare the normal path and deliberate failures with their expected results."),
      ("Explain one result to your partner.", "Which failure did you trigger? Which check caught it?")],
      success="Once the mission is approved and all ten evaluations pass, the JSON dossier becomes available.",
      footnote="The five minutes include reading the results. Evaluations stay deterministic."),
    s("cards", "CHECK THAT THE TEST CAN CATCH A BUG", "The test must notice when a safeguard is removed.",
      "End of checkpoint 4. Based on the notebook’s mutation tests. If time permits, temporarily comment out the repetition guard, rerun the definition and evaluations, then restore it and rerun. Removing only that guard makes the repeat scenario fail. Keep the other loop limits.",
      cards=[("Without the repetition guard", "The model can request the same tool again. The repeat case no longer matches the expected behavior, so its test fails."),
             ("With the guard restored", "Python recognizes the already executed call and stops the loop. The same test passes because the repeated call is blocked.")],
      takeaway="10/10 covers these ten scenarios. A new risk needs a new test case."),
    s("dossier", "WHAT YOU TAKE HOME", "A dossier you can explain and inspect.",
      "0:46–0:48. Readable representation of a mock solution dossier excerpt, not a screenshot of a Gemini call. JSON fields come from incident_dossier. Open the actual session output and find these fields. Download the file and explain the selected failure.",
      metrics=[("INCIDENT", "INC-001"), ("TOOL CALLS", "5"), ("SIMULATED OPERATOR", "APPROVED"), ("EVALUATIONS", "10 / 10")],
      code=FR[17]["code"],
      body="The file contains readings, tool calls and results, the simulated decision and the evaluations. Your chosen failure experiment is included too.",
      takeaway="Pick a decision in the dossier and find the evidence that justifies it.",
      footnote="Shortened excerpt from the solution dossier in mock mode. The file records the exercise; no physical action occurs."),
    s("resources", "KEEP GOING", "Use the code to add your own scenario.",
      "0:48–0:49. Resource titles are clickable in both PDF and PowerPoint. The repository contains participant and solution notebooks in French and English. Reading is optional. Avoid opening pages during the closing minutes if it slows down the discussion.",
      links=[("Workshop repository · French and English notebooks", "Open Colab, inspect the solution and download the materials.", REPO),
             ("Anthropic · Building effective agents", "Further reading on workflows and agents.", "https://www.anthropic.com/engineering/building-effective-agents"),
             ("Google · Gemini API rate limits", "Check the limits before planning concurrent model calls.", "https://ai.google.dev/gemini-api/docs/rate-limits")]),
    s("closing", "THANK YOU", "Which rule would you test in your own field?",
      "0:49–0:50. Take two brief answers. Each pair should name a rule and a case that triggers it. Leave the QR visible. The goal is transfer to their own projects, not a claim that the system is production-ready.",
      prompt="Name an action, then a case where your agent should stop.",
      example="Example: prepare a refund, then block its execution when required approval is missing.",
      speaker="BOSSA Chabel · Software Engineer · ENSGMM\ngithub.com/chabelbossa · linkedin.com/in/chabel-holdo-bossa",
      qr_label="Code and notebooks\nScan to open the repository"),
]
